class EventType:
    # Call Lifecycle
    CALL_STARTED = "CALL_STARTED"
    CALL_TRANSFERRED = "CALL_TRANSFERRED"
    CALL_ENDED = "CALL_ENDED"

    # Topology & Discovery
    STATE_DISCOVERED = "STATE_DISCOVERED"
    STATE_RESOLVED = "STATE_RESOLVED"
    STATE_UNRESOLVED = "STATE_UNRESOLVED"
    ROUTE_COMPLETED = "ROUTE_COMPLETED"
    LOOP_DETECTED = "LOOP_DETECTED"
    DRIFT_DETECTED = "DRIFT_DETECTED"

    # Interaction
    PROMPT_DETECTED = "PROMPT_DETECTED"
    DTMF_SENT = "DTMF_SENT"
    SPEECH_SENT = "SPEECH_SENT"
    TRANSCRIPT_FINAL = "TRANSCRIPT_FINAL"

    # Automation & Escalation
    RUN_ESCALATED = "RUN_ESCALATED"
    REVIEW_VERIFIED = "REVIEW_VERIFIED"
    CONFIDENCE_CHANGED = "CONFIDENCE_CHANGED"

    # System
    ERROR_RAISED = "ERROR_RAISED"
    TEMPLATE_CREATED = "TEMPLATE_CREATED"

    # Runtime Supervision & Recovery (Slice 7)
    HEARTBEAT = "HEARTBEAT"
    RUNTIME_STALLED = "RUNTIME_STALLED"
    WEBSOCKET_DISCONNECTED = "WEBSOCKET_DISCONNECTED"
    WEBSOCKET_RECONNECTED = "WEBSOCKET_RECONNECTED"
    SESSION_RECOVERED = "SESSION_RECOVERED"
    SESSION_TERMINATE = "SESSION_TERMINATE"
    SESSION_TERMINATED = "SESSION_TERMINATED"
    SESSION_CLEANED = "SESSION_CLEANED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    RUNTIME_FAILURE_CAPTURED = "RUNTIME_FAILURE_CAPTURED"

    # Replay & Session Reconstruction
    CALL_CONNECTED = "CALL_CONNECTED"
    CALL_COMPLETED = "CALL_COMPLETED"
    NODE_DISCOVERED = "NODE_DISCOVERED"
    EDGE_DISCOVERED = "EDGE_DISCOVERED"
    PATH_ADVANCED = "PATH_ADVANCED"
    GRAPH_UPDATED = "GRAPH_UPDATED"
    REPLAY_LOADED = "REPLAY_LOADED"

    # Telecom Validation (Slice 8)
    TELECOM_TEST_STARTED = "TELECOM_TEST_STARTED"
    TELECOM_TEST_COMPLETED = "TELECOM_TEST_COMPLETED"
    TELECOM_TEST_FAILED = "TELECOM_TEST_FAILED"
    TELECOM_TEST_ABORTED = "TELECOM_TEST_ABORTED"
    SAFETY_GUARD_TRIGGERED = "SAFETY_GUARD_TRIGGERED"
    TEST_EVIDENCE_READY = "TEST_EVIDENCE_READY"