"""GapTask system — the cognitive agenda of the IVR mapping agent.

The agent's entire behavior is:
    pop highest-priority gap → go answer it → update IvrMapper → repeat

This module defines:
- GapType enum (all 14 gap types, three sources)
- GapStatus state machine (PENDING → IN_PROGRESS → terminal)
- GapTask dataclass (all fields for Phase 1, placeholders for Phase 2+)
- GapTaskQueue (priority queue + done() termination logic)
- Priority scoring sub-components (all normalized to [0.0, 1.0])

STATUS: Phase 1 design — no engine wiring yet.
DiscoveryEngine, ValidationEngine, HypothesisEngine are aspirational
components that WILL produce GapTasks; they do not exist in the codebase
as of 2026-05-31. The queue and dataclass are implementation-ready.
"""

from __future__ import annotations

import heapq
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import StrEnum
from typing import Any


# ---------------------------------------------------------------------------
# Gap taxonomy
# ---------------------------------------------------------------------------

class GapType(StrEnum):
    # -- OBSERVATION-DRIVEN (generated by DiscoveryEngine from SessionObservations) --

    UNVISITED_ANNOUNCED_OPTION = "unvisited_announced_option"
    """Option was announced in a prompt (present in PromptNode.announced_options)
    but has never been pressed. The most common gap type in early exploration."""

    UNCONFIRMED_EDGE = "unconfirmed_edge"
    """Edge traversed exactly once (BranchObservation.count == 1). Needs a second
    confirmation pass to raise confidence above the single-observation floor."""

    VARIABLE_BEHAVIOR = "variable_behavior"
    """Same DTMF input at the same node yielded different next-node outcomes on
    different calls. Indicates time-of-day routing, load balancing, or a bug."""

    AMBIGUOUS_PROMPT = "ambiguous_prompt"
    """Prompt transcript is present but PromptClassification.confidence < 0.50.
    The parser could not reliably determine intent or extract options."""

    TIMEOUT_PATH_UNKNOWN = "timeout_path_unknown"
    """What the IVR does if no DTMF is pressed within its timeout window has never
    been observed for this node. Some IVRs repeat; others route to agent."""

    POST_AUTH_UNKNOWN = "post_auth_unknown"
    """A subtree sits behind an authentication gate (PromptIntent.AUTH_GATE,
    Phase 2 node type) that has never been successfully traversed."""

    # -- VALIDATION-DRIVEN (generated by ValidationEngine) --

    STRUCTURAL_DRIFT = "structural_drift"
    """Node was reached on a recent call but its branch structure differs from
    what is stored in the IvrMapper graph. Options have been added or removed."""

    CONTENT_DRIFT = "content_drift"
    """Node was reached and its structure matches, but the prompt wording differs
    significantly from the stored canonical text (edit distance > threshold)."""

    CONFIDENCE_DECAY = "confidence_decay"
    """Node's stored confidence has fallen below the reconfirmation threshold due
    to elapsed time without a fresh observation. Knowledge is going stale."""

    DEPRECATED_CANDIDATE = "deprecated_candidate"
    """Node has been unreachable on 2+ consecutive attempts. May have been removed
    from the IVR. Needs one more confirmation before marking as deprecated."""

    # -- HYPOTHESIS-DRIVEN (generated by HypothesisEngine) --

    HYPOTHESIS_TEST = "hypothesis_test"
    """Navigate to a predicted location to confirm or refute a structural
    hypothesis (e.g., "billing path likely ends in HUMAN_HANDOFF after 3 hops")."""

    CROSS_IVR_PATTERN = "cross_ivr_pattern"
    """Test whether a pattern observed in other mapped IVRs applies here
    (e.g., pressing 0 at any menu routes to operator)."""

    # -- HUMAN-GENERATED --

    MANUAL_INVESTIGATION = "manual_investigation"
    """Operator flagged a node or path for deeper investigation. Free-form
    context stored in GapTask.operator_context."""

    EXTRACTION_SETUP = "extraction_setup"
    """Operator wants to configure status-extraction automation for a specific
    node (e.g., "extract account balance from this prompt"). Phase 2 feature."""


# ---------------------------------------------------------------------------
# Gap status state machine
# ---------------------------------------------------------------------------

class GapStatus(StrEnum):
    PENDING = "pending"
    """Waiting to be dispatched to a call session."""

    IN_PROGRESS = "in_progress"
    """A call session is actively navigating toward this gap's target."""

    RESOLVED = "resolved"
    """Gap was answered — knowledge updated, confidence raised."""

    FAILED = "failed"
    """Navigation attempt failed (call dropped, auth blocked, etc.).
    Retryable: a new GapTask may be created with retry_count incremented."""

    DEFERRED = "deferred"
    """Gap cannot be worked right now (e.g., rate limit, time-of-day
    restriction). Will be re-activated when deferred_until elapses."""

    SUPERSEDED = "superseded"
    """A structural change (node removed, path changed) made this gap
    irrelevant. Can be reached from PENDING, IN_PROGRESS, or DEFERRED."""


# ---------------------------------------------------------------------------
# Priority scoring
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class PriorityScoreBreakdown:
    """All sub-scores normalized to [0.0, 1.0]. Final score also in [0.0, 1.0]."""

    impact_score: float
    """Does this path lead toward a high-value endpoint?

    Computed by graph reachability from the gap's target_node_key:
    - 1.0  if the target node IS a human-handoff / extraction point
    - 0.85 if a known human-handoff or extraction node is within 2 hops
    - 0.60 if within 3–5 hops
    - 0.30 if reachable but > 5 hops or unknown distance
    - 0.10 if the path leads to a known dead-end (no outbound edges)
    - 0.05 default when reachability cannot be computed (unexplored subtree)

    Weight: 0.35
    """

    urgency_score: float
    """How stale or time-sensitive is this gap?

    Computed from age and gap type:
    - MANUAL_INVESTIGATION / EXTRACTION_SETUP: urgency = operator_priority (see below)
    - STRUCTURAL_DRIFT / CONTENT_DRIFT: urgency = min(1.0, days_since_last_visit / 7)
    - CONFIDENCE_DECAY: urgency = 1.0 - current_confidence  (lower confidence → more urgent)
    - DEPRECATED_CANDIDATE: urgency = min(1.0, unreachable_count / 3)
    - All others: urgency = min(1.0, days_since_created / 30)

    Weight: 0.25
    """

    confidence_benefit: float
    """How much does filling this gap improve the world model?

    Named "confidence_penalty" in the spec — here clarified as the BENEFIT of
    filling the gap (a low-confidence or unknown node has HIGH benefit, so the
    weight is positive and the score increases priority).

    Computed:
    - UNVISITED_ANNOUNCED_OPTION: 1.0 (zero knowledge of this branch)
    - POST_AUTH_UNKNOWN: 1.0 (entire subtree unknown)
    - HYPOTHESIS_TEST / CROSS_IVR_PATTERN: 0.7 (structured uncertainty)
    - UNCONFIRMED_EDGE: 1.0 - BranchObservation.confidence
    - AMBIGUOUS_PROMPT: 1.0 - PromptClassification.confidence (clamped to [0,1])
    - CONFIDENCE_DECAY: 1.0 - PromptNode.confidence
    - STRUCTURAL_DRIFT / CONTENT_DRIFT / VARIABLE_BEHAVIOR: 0.8
    - DEPRECATED_CANDIDATE: 0.5 (partial knowledge, outcome uncertain)
    - MANUAL_INVESTIGATION: 0.6
    - EXTRACTION_SETUP: 0.4 (node is known; setup is administrative)
    - TIMEOUT_PATH_UNKNOWN: 0.9

    Weight: 0.20
    """

    user_priority: float
    """Operator-assigned priority in [0.0, 1.0]. Default 0.5 (neutral).

    Operators can override to 1.0 ("investigate immediately") or 0.0
    ("deprioritize"). Stored as GapTask.operator_priority.

    Weight: 0.15
    """

    freshness_bonus: float
    """Recently discovered gaps get a small boost to avoid starvation.

    freshness_bonus = max(0.0, 1.0 - (hours_since_created / 24))

    Decays linearly from 1.0 at creation to 0.0 after 24 hours.

    Weight: 0.05
    """

    @property
    def final_score(self) -> float:
        return (
            0.35 * self.impact_score
            + 0.25 * self.urgency_score
            + 0.20 * self.confidence_benefit
            + 0.15 * self.user_priority
            + 0.05 * self.freshness_bonus
        )


def example_high_priority_score() -> PriorityScoreBreakdown:
    """Example: unexplored option on the billing path of a major bank.

    Scenario: PromptNode at "For billing press 1" — option "1" is in
    announced_options but BranchObservation.count == 0. The billing path
    in similar IVRs ends in a HUMAN_HANDOFF within 2 hops.

    Sub-scores:
    - impact_score    = 0.85  (human-handoff within 2 hops via cross-IVR pattern)
    - urgency_score   = 0.80  (gap created 24 days ago, min(1.0, 24/30))
    - confidence_benefit = 1.0  (UNVISITED_ANNOUNCED_OPTION: zero knowledge)
    - user_priority   = 0.80  (operator marked billing paths as high priority)
    - freshness_bonus = 0.0   (24+ hours old)

    final = 0.35*0.85 + 0.25*0.80 + 0.20*1.0 + 0.15*0.80 + 0.05*0.0
          = 0.2975   + 0.2000   + 0.2000   + 0.1200   + 0.0000
          = 0.817
    """
    return PriorityScoreBreakdown(
        impact_score=0.85,
        urgency_score=0.80,
        confidence_benefit=1.0,
        user_priority=0.80,
        freshness_bonus=0.0,
    )


def example_low_priority_score() -> PriorityScoreBreakdown:
    """Example: timeout behavior on a rarely-used submenu.

    Scenario: TIMEOUT_PATH_UNKNOWN gap for a node deep in the "fax number
    update" submenu. Node is visited by < 1% of real callers. No downstream
    human-handoff within known graph. Gap is 2 hours old.

    Sub-scores:
    - impact_score    = 0.10  (leads to a dead-end subtree, no high-value endpoint)
    - urgency_score   = 0.003 (min(1.0, 2/30 days ≈ 0.003))
    - confidence_benefit = 0.9  (TIMEOUT_PATH_UNKNOWN)
    - user_priority   = 0.20  (operator explicitly deprioritized fax subtree)
    - freshness_bonus = 0.92  (2 hours old: 1.0 - 2/24 ≈ 0.92)

    final = 0.35*0.10 + 0.25*0.003 + 0.20*0.9 + 0.15*0.20 + 0.05*0.92
          = 0.0350   + 0.0008     + 0.1800   + 0.0300   + 0.0460
          = 0.292

    The freshness_bonus temporarily inflates this; after 24h it falls to ~0.22.
    """
    return PriorityScoreBreakdown(
        impact_score=0.10,
        urgency_score=0.003,
        confidence_benefit=0.9,
        user_priority=0.20,
        freshness_bonus=0.92,
    )


# ---------------------------------------------------------------------------
# GapTask dataclass
# ---------------------------------------------------------------------------

@dataclass
class GapTask:
    """The atomic unit of agent work.

    Each instance represents one thing the agent does not know and wants to
    learn. The queue sorts by priority_score (descending).

    Phase 1 fields are all populated. Phase 2 placeholder fields are noted
    with # PHASE-2 comments; they default to None and are safe to ignore.
    """

    # -- Identity --
    gap_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    """Stable UUID assigned at creation. Never changes."""

    gap_type: GapType = GapType.UNVISITED_ANNOUNCED_OPTION
    """Determines which engine generated this gap and how to work it."""

    status: GapStatus = GapStatus.PENDING
    """Current state in the GapStatus state machine."""

    # -- Targeting --
    target_ivr_id: str = ""
    """Which IVR system this gap belongs to (phone number or logical ID)."""

    target_node_key: str | None = None
    """Canonical PromptNode key (IvrMapper._nodes key) this gap targets.
    None for gaps that don't map to a specific existing node
    (e.g., HYPOTHESIS_TEST for a predicted but not-yet-seen node)."""

    target_option: str | None = None
    """DTMF option within the target node, if applicable.
    Set for UNVISITED_ANNOUNCED_OPTION, UNCONFIRMED_EDGE, VARIABLE_BEHAVIOR."""

    planned_path: list[str] = field(default_factory=list)
    """DTMF sequence to navigate from the IVR root to the target node.
    Populated by the path planner before dispatching. Empty = not yet planned."""

    # -- Priority --
    priority_score: float = 0.0
    """Computed priority in [0.0, 1.0]. Higher = worked first.
    Recalculated by the queue whenever sub-score inputs change."""

    score_breakdown: PriorityScoreBreakdown | None = None
    """Sub-score breakdown for debugging and operator visibility."""

    operator_priority: float = 0.5
    """Operator-assigned weight in [0.0, 1.0]. Default 0.5 (neutral)."""

    # -- Provenance --
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    source_session_id: str | None = None
    """Session that triggered this gap (if observation-driven)."""

    source_engine: str | None = None
    """Which engine created this gap: 'discovery', 'validation', 'hypothesis',
    or 'operator'."""

    # -- Lifecycle tracking --
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    in_progress_since: datetime | None = None
    """When the gap entered IN_PROGRESS. Used to detect stuck sessions."""

    resolved_at: datetime | None = None
    deferred_until: datetime | None = None
    """If status == DEFERRED, re-activate when datetime.now(utc) >= deferred_until."""

    retry_count: int = 0
    """How many FAILED attempts before this gap was re-queued."""

    max_retries: int = 3
    """FAILED gaps beyond max_retries are not re-queued; they stay FAILED."""

    superseded_reason: str | None = None
    """Human-readable reason why this gap was superseded (e.g., 'node removed
    in structural update session-abc123')."""

    # -- Evidence collected during resolution --
    resolution_session_id: str | None = None
    """Session that resolved this gap."""

    resolution_notes: str | None = None
    """Free-form notes from the resolution pass (what was found)."""

    # -- Human/operator context --
    operator_context: str | None = None
    """Free-form text from the operator for MANUAL_INVESTIGATION gaps."""

    operator_label: str | None = None
    """Short label for display in the analyst UI."""

    # -- Gap-type-specific metadata (all optional) --
    observed_confidence: float | None = None
    """For AMBIGUOUS_PROMPT / CONFIDENCE_DECAY: the last recorded confidence."""

    variable_outcomes: list[str] = field(default_factory=list)
    """For VARIABLE_BEHAVIOR: list of distinct next_node_keys observed."""

    unreachable_count: int = 0
    """For DEPRECATED_CANDIDATE: how many consecutive times the node was
    unreachable."""

    hypothesis_id: str | None = None
    """For HYPOTHESIS_TEST / CROSS_IVR_PATTERN: reference to the hypothesis
    record that spawned this gap. PHASE-2: HypothesisEngine will populate."""

    # PHASE-2 placeholders (safe to ignore in Phase 1)
    extraction_config: dict[str, Any] | None = None
    # PHASE-2: ExtractionSetup config blob for EXTRACTION_SETUP gaps.

    auth_credential_ref: str | None = None
    # PHASE-2: Reference to a credential vault entry for POST_AUTH_UNKNOWN gaps.

    cross_ivr_pattern_ref: str | None = None
    # PHASE-2: Pattern library reference for CROSS_IVR_PATTERN gaps.

    # -- Heap ordering support --
    def __lt__(self, other: "GapTask") -> bool:
        # Higher score = higher priority; invert for min-heap.
        return self.priority_score > other.priority_score


# ---------------------------------------------------------------------------
# State machine transitions
# ---------------------------------------------------------------------------

class GapTaskTransitionError(Exception):
    pass


def transition(gap: GapTask, new_status: GapStatus, **kwargs: Any) -> None:
    """Apply a state transition, enforcing the state machine rules.

    Valid transitions:
      PENDING     → IN_PROGRESS   (session dispatched to work this gap)
      PENDING     → DEFERRED      (rate limit, time restriction, etc.)
      PENDING     → SUPERSEDED    (structural change obsoleted the gap)
      IN_PROGRESS → RESOLVED      (gap answered, knowledge updated)
      IN_PROGRESS → FAILED        (call dropped, auth blocked, etc.)
      IN_PROGRESS → DEFERRED      (session hit a hard stop mid-navigation)
      IN_PROGRESS → SUPERSEDED    (structural change while call was in flight)
      DEFERRED    → PENDING       (deferred_until elapsed; re-queued)
      DEFERRED    → SUPERSEDED    (structural change while gap was deferred)
      FAILED      → PENDING       (retry, if retry_count < max_retries)

    Terminal states: RESOLVED, SUPERSEDED.
    FAILED is terminal when retry_count >= max_retries.
    """
    current = gap.status
    allowed: dict[GapStatus, set[GapStatus]] = {
        GapStatus.PENDING: {
            GapStatus.IN_PROGRESS,
            GapStatus.DEFERRED,
            GapStatus.SUPERSEDED,
        },
        GapStatus.IN_PROGRESS: {
            GapStatus.RESOLVED,
            GapStatus.FAILED,
            GapStatus.DEFERRED,
            GapStatus.SUPERSEDED,
        },
        GapStatus.DEFERRED: {
            GapStatus.PENDING,
            GapStatus.SUPERSEDED,
        },
        GapStatus.FAILED: {
            GapStatus.PENDING,  # retry only
        },
        GapStatus.RESOLVED: set(),   # terminal
        GapStatus.SUPERSEDED: set(), # terminal
    }
    if new_status not in allowed.get(current, set()):
        raise GapTaskTransitionError(
            f"Invalid transition: {current} → {new_status} for gap {gap.gap_id}"
        )
    if new_status == GapStatus.FAILED and gap.retry_count >= gap.max_retries:
        # FAILED with no retries left: stays terminal, block re-queue attempts.
        pass
    now = datetime.now(timezone.utc)
    gap.status = new_status
    gap.updated_at = now
    if new_status == GapStatus.IN_PROGRESS:
        gap.in_progress_since = now
    elif new_status == GapStatus.RESOLVED:
        gap.resolved_at = now
        gap.resolution_session_id = kwargs.get("session_id")
        gap.resolution_notes = kwargs.get("notes")
    elif new_status == GapStatus.DEFERRED:
        gap.deferred_until = kwargs.get("until")
    elif new_status == GapStatus.SUPERSEDED:
        gap.superseded_reason = kwargs.get("reason", "structural change")
    elif new_status == GapStatus.PENDING and current == GapStatus.FAILED:
        gap.retry_count += 1


# ---------------------------------------------------------------------------
# GapTaskQueue — the agent's cognitive agenda
# ---------------------------------------------------------------------------

class GapTaskQueue:
    """Priority queue of GapTasks sorted by priority_score (highest first).

    This is the agent's cognitive agenda. The loop is:
        while not queue.done():
            gap = queue.pop()
            result = session_runner.execute(gap)
            queue.handle_result(gap, result)

    Thread-safety: not thread-safe by default. Wrap in a lock for concurrent
    session dispatch.
    """

    DEFAULT_THRESHOLD: float = 0.10
    """Gaps below this priority_score are considered not worth working.
    All-remaining-below-threshold is one of the two done() conditions."""

    def __init__(self, threshold: float = DEFAULT_THRESHOLD) -> None:
        self._heap: list[GapTask] = []
        self._all: dict[str, GapTask] = {}  # gap_id → GapTask (all states)
        self._threshold = threshold

    def push(self, gap: GapTask) -> None:
        """Add a new PENDING gap. Raises if a gap with the same ID already exists."""
        if gap.gap_id in self._all:
            raise ValueError(f"Gap {gap.gap_id} already in queue")
        self._all[gap.gap_id] = gap
        if gap.status == GapStatus.PENDING:
            heapq.heappush(self._heap, gap)

    def pop(self) -> GapTask | None:
        """Return the highest-priority PENDING gap, or None if none available.

        Skips gaps that are no longer PENDING (they may have been superseded
        or transitioned externally while on the heap).
        """
        while self._heap:
            gap = heapq.heappop(self._heap)
            if gap.status == GapStatus.PENDING:
                return gap
        return None

    def requeue(self, gap: GapTask) -> None:
        """Push a gap back onto the heap (after DEFERRED→PENDING or FAILED→PENDING).

        The gap must already be in self._all and have status PENDING.
        """
        if gap.gap_id not in self._all:
            raise ValueError(f"Gap {gap.gap_id} not known to this queue")
        heapq.heappush(self._heap, gap)

    def supersede_by_node(self, node_key: str, reason: str) -> list[str]:
        """Supersede all non-terminal gaps targeting node_key.

        Called when IvrMapper detects that a node has been removed or
        fundamentally restructured. Returns list of superseded gap IDs.
        """
        superseded_ids: list[str] = []
        for gap in self._all.values():
            if (
                gap.target_node_key == node_key
                and gap.status not in (GapStatus.RESOLVED, GapStatus.SUPERSEDED)
            ):
                transition(gap, GapStatus.SUPERSEDED, reason=reason)
                superseded_ids.append(gap.gap_id)
        return superseded_ids

    def activate_deferred(self) -> list[GapTask]:
        """Re-activate all DEFERRED gaps whose deferred_until has elapsed."""
        now = datetime.now(timezone.utc)
        reactivated: list[GapTask] = []
        for gap in self._all.values():
            if (
                gap.status == GapStatus.DEFERRED
                and gap.deferred_until is not None
                and now >= gap.deferred_until
            ):
                transition(gap, GapStatus.PENDING)
                self.requeue(gap)
                reactivated.append(gap)
        return reactivated

    # -- Cognitive query interface --

    def unknown_territory(self) -> list[GapTask]:
        """What do I know NOTHING about?

        Returns PENDING gaps of types that represent complete absence of
        knowledge: UNVISITED_ANNOUNCED_OPTION, HYPOTHESIS_TEST,
        POST_AUTH_UNKNOWN, TIMEOUT_PATH_UNKNOWN.
        """
        zero_knowledge_types = {
            GapType.UNVISITED_ANNOUNCED_OPTION,
            GapType.HYPOTHESIS_TEST,
            GapType.POST_AUTH_UNKNOWN,
            GapType.TIMEOUT_PATH_UNKNOWN,
        }
        return [
            g for g in self._all.values()
            if g.status == GapStatus.PENDING and g.gap_type in zero_knowledge_types
        ]

    def uncertain_territory(self) -> list[GapTask]:
        """What do I THINK I know but might be wrong about?

        Returns PENDING gaps of types that represent degraded or contested
        knowledge: CONFIDENCE_DECAY, STRUCTURAL_DRIFT, CONTENT_DRIFT,
        VARIABLE_BEHAVIOR, UNCONFIRMED_EDGE.
        """
        uncertain_types = {
            GapType.CONFIDENCE_DECAY,
            GapType.STRUCTURAL_DRIFT,
            GapType.CONTENT_DRIFT,
            GapType.VARIABLE_BEHAVIOR,
            GapType.UNCONFIRMED_EDGE,
        }
        return [
            g for g in self._all.values()
            if g.status == GapStatus.PENDING and g.gap_type in uncertain_types
        ]

    def highest_value_next(self) -> GapTask | None:
        """What is the most valuable thing to learn next?

        Peeks at the top of the heap without popping. Returns the highest
        priority_score PENDING gap, or None.
        """
        # Drain stale entries to find the live top.
        while self._heap and self._heap[0].status != GapStatus.PENDING:
            heapq.heappop(self._heap)
        return self._heap[0] if self._heap else None

    def pending_count(self) -> int:
        return sum(1 for g in self._all.values() if g.status == GapStatus.PENDING)

    def in_progress_count(self) -> int:
        return sum(1 for g in self._all.values() if g.status == GapStatus.IN_PROGRESS)

    def done(self) -> bool:
        """Is the agent done?

        Two exit conditions:
        1. No PENDING or IN_PROGRESS gaps remain (queue fully drained).
        2. All remaining PENDING gaps are below the priority threshold AND
           no gaps are currently IN_PROGRESS.

        Condition 2 prevents premature done() while a session is active.
        Condition 1 is the clean termination case.

        The threshold is configurable at construction time.
        """
        pending = [g for g in self._all.values() if g.status == GapStatus.PENDING]
        in_progress = [g for g in self._all.values() if g.status == GapStatus.IN_PROGRESS]

        if in_progress:
            # A session is active; we are not done.
            return False

        if not pending:
            # Nothing left to do.
            return True

        # Done if every remaining gap is below the threshold.
        return all(g.priority_score < self._threshold for g in pending)

    def summary(self) -> dict[str, int]:
        """Status counts for logging and operator UI."""
        counts: dict[str, int] = {s: 0 for s in GapStatus}
        for gap in self._all.values():
            counts[gap.status] += 1
        return counts
