from __future__ import annotations

from typing import Protocol


class TelephonyClient(Protocol):
    def dial(self, target_number: str) -> str: ...

    def send_dtmf(self, session_id: str, digits: str) -> None: ...

    def play_clip(self, session_id: str, file_path: str) -> None: ...

    def say(self, session_id: str, text: str) -> None: ...

    def hangup(self, session_id: str) -> None: ...