class EventType:
    # Call Lifecycle
    CALL_STARTED = "CALL_STARTED"
    CALL_TRANSFERRED = "CALL_TRANSFERRED"
    CALL_ENDED = "CALL_ENDED"

    # Topology & Discovery
    STATE_DISCOVERED = "STATE_DISCOVERED"
    STATE_RESOLVED = "STATE_RESOLVED"
    STATE_UNRESOLVED = "STATE_UNRESOLVED"
    ROUTE_COMPLETED = "ROUTE_COMPLETED"
    LOOP_DETECTED = "LOOP_DETECTED"
    DRIFT_DETECTED = "DRIFT_DETECTED"

    # Interaction
    PROMPT_DETECTED = "PROMPT_DETECTED"
    DTMF_SENT = "DTMF_SENT"
    SPEECH_SENT = "SPEECH_SENT"
    TRANSCRIPT_FINAL = "TRANSCRIPT_FINAL"

    # Automation & Escalation
    RUN_ESCALATED = "RUN_ESCALATED"
    REVIEW_VERIFIED = "REVIEW_VERIFIED"
    CONFIDENCE_CHANGED = "CONFIDENCE_CHANGED"

    # System
    ERROR_RAISED = "ERROR_RAISED"
    TEMPLATE_CREATED = "TEMPLATE_CREATED"
