#!/bin/bash
# IVR Batch Worker — runs all enabled jobs sequentially.
# This file is generated by setup.sh. Edit ~/ivr/run_ivr_batch.sh directly
# after installation, not this template.
set -euo pipefail

IVR_DIR="$HOME/ivr"
JOBS_FILE="$IVR_DIR/jobs.json"
RESULTS_DIR="$IVR_DIR/results"
PROBE="$IVR_DIR/probe.py"
SUITE="$IVR_DIR/suite.json"

# REPO_PATH is substituted by setup.sh
REPO_PATH="__REPO_PATH__"
export PYTHONPATH="$REPO_PATH"

log() { echo "[$(date -Iseconds)] $*"; }

if [[ ! -f "$JOBS_FILE" ]]; then
    log "ERROR: $JOBS_FILE not found — create it from jobs.json template"
    exit 1
fi

if [[ ! -f "$PROBE" ]]; then
    log "ERROR: $PROBE not found — run setup.sh again"
    exit 1
fi

log "Starting IVR batch run"

python3 - <<PYEOF
import json, subprocess, sys, os
from datetime import datetime, timezone

jobs_file   = os.path.expanduser("~/ivr/jobs.json")
results_dir = os.path.expanduser("~/ivr/results")
probe       = os.path.expanduser("~/ivr/probe.py")
suite       = os.path.expanduser("~/ivr/suite.json")

jobs = json.load(open(jobs_file))

for job in jobs:
    if not job.get("enabled", False):
        print(f"[{datetime.now(timezone.utc).isoformat()}] Skipping {job['name']} (disabled)")
        continue

    name = job["name"]
    card = str(job["card_number"])
    result_dir = f"{results_dir}/{name}"
    os.makedirs(result_dir, exist_ok=True)

    print(f"[{datetime.now(timezone.utc).isoformat()}] Running job: {name}", flush=True)

    try:
        proc = subprocess.run(
            [sys.executable, probe, "--card", card, "--suite", suite, "--format", "json"],
            capture_output=True, text=True, timeout=300
        )
        if proc.returncode == 0 and proc.stdout.strip():
            outcome = json.loads(proc.stdout.strip())
        else:
            outcome = {
                "status": "ERROR",
                "transcript": proc.stderr.strip() or "probe exited with non-zero status",
                "matched_keyword": ""
            }
    except subprocess.TimeoutExpired:
        outcome = {"status": "ERROR", "transcript": "probe timed out after 300s", "matched_keyword": ""}
    except Exception as exc:
        outcome = {"status": "ERROR", "transcript": str(exc), "matched_keyword": ""}

    result = {
        "status": outcome.get("status", "ERROR"),
        "transcript": outcome.get("transcript", ""),
        "timestamp": datetime.now(timezone.utc).isoformat()
    }

    with open(f"{result_dir}/latest.json", "w") as f:
        json.dump(result, f, indent=2)

    print(f"[{datetime.now(timezone.utc).isoformat()}] {name}: {result['status']}", flush=True)

print(f"[{datetime.now(timezone.utc).isoformat()}] Batch complete")
PYEOF
